import type { Workflow } from '@/modules/orchestration/workflows/workflow.types.js';

export const builtInWorkflows: Workflow[] = [
  {
    id: 'agent_team',
    name: 'Agent team',
    description: 'A coordinator reads the goal and active CLI instances, assigns work, then collects the result.',
    trigger: 'manual',
    isBuiltin: true,
    nodes: [],
  },
  {
    id: 'multi_model_review',
    name: 'Multi-model review',
    description: 'Enabled CLI agents review the same goal separately, then one enabled agent aggregates the result.',
    trigger: 'manual',
    isBuiltin: true,
    nodes: [
      {
        id: 'codex_review',
        adapterId: 'codex',
        prompt: 'Review the requested change for edge cases, regressions, and missing validation. Respond in the same language as the user request.',
        inputs: [],
        output: 'both',
        onFail: 'continue',
      },
      {
        id: 'gemini_review',
        adapterId: 'gemini',
        prompt: 'Review the requested change for security, scale, and user-experience risks. Respond in the same language as the user request.',
        inputs: [],
        output: 'both',
        onFail: 'continue',
      },
      {
        id: 'claude_review',
        adapterId: 'claude-code',
        prompt: 'Review the requested change for architecture and maintainability. Respond in the same language as the user request.',
        inputs: [],
        output: 'both',
        onFail: 'continue',
      },
      {
        id: 'aggregate',
        adapterId: 'claude-code',
        prompt: 'Aggregate the prior reviews into a concise prioritized report. Respond in the same language as the user request.',
        inputs: ['codex_review', 'gemini_review', 'claude_review'],
        output: 'message',
        onFail: 'abort',
      },
    ],
  },
  {
    id: 'sequential_handoff',
    name: 'Sequential handoff',
    description: 'Agents plan, implement, and review in order. Disabled CLI steps are skipped.',
    trigger: 'manual',
    isBuiltin: true,
    nodes: [
      {
        id: 'architect',
        adapterId: 'claude-code',
        prompt: 'Create a concise, actionable implementation plan for the requested change. Respond in the same language as the user request.',
        inputs: [],
        output: 'message',
        onFail: 'abort',
      },
      {
        id: 'implement',
        adapterId: 'codex',
        prompt: 'Implement the requested change using the plan from the previous step. Summarize progress in the same language as the user request.',
        inputs: ['architect'],
        output: 'both',
        onFail: 'abort',
      },
      {
        id: 'review',
        adapterId: 'gemini',
        prompt: 'Review the implementation and call out any remaining issues. Respond in the same language as the user request.',
        inputs: ['implement'],
        output: 'message',
        onFail: 'continue',
      },
    ],
  },
  {
    id: 'adversarial_debate',
    name: 'Decision debate',
    description: 'Agents propose, critique, respond, and produce a final recommendation.',
    trigger: 'manual',
    isBuiltin: true,
    nodes: [
      {
        id: 'proposal',
        adapterId: 'claude-code',
        prompt: 'Propose the best solution for the requested change. Respond in the same language as the user request.',
        inputs: [],
        output: 'message',
        onFail: 'abort',
      },
      {
        id: 'critique',
        adapterId: 'codex',
        prompt: 'Critique the proposal and offer a concrete alternative. Respond in the same language as the user request.',
        inputs: ['proposal'],
        output: 'message',
        onFail: 'abort',
      },
      {
        id: 'response',
        adapterId: 'claude-code',
        prompt: 'Respond to the critique and revise the approach if needed. Respond in the same language as the user request.',
        inputs: ['critique'],
        output: 'message',
        onFail: 'abort',
      },
      {
        id: 'judge',
        adapterId: 'gemini',
        prompt: 'Judge the debate and produce a final recommendation. Respond in the same language as the user request.',
        inputs: ['response'],
        output: 'message',
        onFail: 'abort',
      },
    ],
  },
];
